### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by MarcinHoppe**
Just a few minor fixes in the commit. I will leave a few more questions about other parts of the article.

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
https://github.com/MarcinHoppe/blog.scooletz.com-posts/blame/capabilities-comments/2020-06-08-capability-based-security.md#L27:

> As we can see, the columns in here could be a representation for ACLs.

I think the *table* is the ACL. The columns are resources, rows are identities, and cells represent privileges.

**Comment by MarcinHoppe** [comment]
https://github.com/MarcinHoppe/blog.scooletz.com-posts/blame/capabilities-comments/2020-06-08-capability-based-security.md#L93:

> In systems where the storage/retrieval of data is explicit, the indexing or tagging can be used. If you think about capabilities being stored in an array, you could use an index in the array, assuming that the location of a capability is not changed. Once you write it to a file and read again, you'll be able to read it again from the list. Similarly, tagging, naming can be used.

I think I'd like to understand this a bit better. Maybe an example could help?

I suspect that the indexing idea is inspired by file descriptors (or `HANDLE`s on Windows) but I don't quite understand the tagging idea.

**Comment by MarcinHoppe** [comment]
https://github.com/MarcinHoppe/blog.scooletz.com-posts/blame/capabilities-comments/2020-06-08-capability-based-security.md#L103:

> If a process is in capability mode, it is denied access to global namespaces such as the file system, PIDs and more.

I'd maybe add that this means the process in capability mode is essentially a sandbox that is _only_ capable of accessing resources it has a capability for.

**Comment by Scooletz** [comment]
> 
> 
> https://github.com/MarcinHoppe/blog.scooletz.com-posts/blame/capabilities-comments/2020-06-08-capability-based-security.md#L27:
> 
> > As we can see, the columns in here could be a representation for ACLs.
> 
> I think the _table_ is the ACL. The columns are resources, rows are identities, and cells represent privileges.

AFAIK, ACLs are attached to objects ([wiki](https://en.wikipedia.org/wiki/Access-control_list), in this case - files, so in my understanding, they are columns in here.

> I think I'd like to understand this a bit better. Maybe an example could help?

Added in https://github.com/Scooletz/blog.scooletz.com-posts/commit/5f387be5c5b6b51f0e276e00c4a3e83a8991ff29



>>  If a process is in capability mode, it is denied access to global namespaces such as the file system, PIDs and more.

> I'd maybe add that this means the process in capability mode is essentially a sandbox that is only capable of accessing resources it has a capability for.

Actually, I wanted to write it like this, but in the Capsicum papers (not peppers 😂 ) they used this phrasing. As I'm not that familiar with Linux Kernel, I wanted to stick to exclusion of resources rather than claiming that it's capabilities only. Being given that verifying it would take much more, I'll stick to the phrasing as it is.

**Comment by Scooletz** [comment]
Not sure if you got a notification @MarcinHoppe Ping ;-)

**Comment by MarcinHoppe** [comment]
Thanks, the example is great and explanations make perfect sense -- perhaps it's worth including them in the article?

**Comment by Scooletz** [comment]
I'll amend it with 

1. ACLs explanation
1. Capsicum note about the reasoning

The index has already been addressed.

**Pull request merged**
